-- 002_dev_users.sql
-- DEV-ONLY seed users. Clearly marked placeholders. NO real secrets.
-- Passwords are scrypt (cost N=2^17, r=8, p=1) hashes generated by
-- apps/backend/src/modules/identity/password.ts hashPassword().
--
--   admin@hosifest.test     / DevAdmin!2024     -> ADMIN
--   finance@hosifest.test   / DevFinance!2024   -> FINANCE
--   checkin@hosifest.test   / DevCheckin!2024   -> ATTENDANCE
--   souvenir@hosifest.test  / DevSouvenir!2024  -> ADMIN (maps to ADMIN because rbac.ts has no SOUVENIR role)
--
-- !! PRODUCTION WARNING !!
-- These accounts MUST NOT be loaded in production. Delete these rows or rotate
-- the passwords before any production deploy. Do not commit real credentials.

INSERT INTO users (id, email, full_name, password_hash, status) VALUES
  ('33333333-3333-4333-8333-333333333301', 'admin@hosifest.test', 'Dev Super Admin',
   'scrypt$6a4186db9f74760a5e7bae1fcf728f6c$c21a5239f2b6d8a8ed1f81d0446ef4488baf225dcb07510e5dec3646690db8e5aa0fa3626cfe89c4565755b40d4e726fe343da2a70010f3040b1a0d550cb1d72', 'ACTIVE'),
  ('33333333-3333-4333-8333-333333333302', 'finance@hosifest.test', 'Dev Finance',
   'scrypt$83298b77132b064c4c9ca92107b91799$b8bb7d033b7db9d474a5970bc588295f7d68e31a87aa8038e7e8363e2a05643aa715100e0500d9b5a8150177e1443a3663cb70aff6594fe73689680c0c599b23', 'ACTIVE'),
  ('33333333-3333-4333-8333-333333333303', 'checkin@hosifest.test', 'Dev Check-in',
   'scrypt$5f7d322ee0643e93dc145a398cbecf9e$ac73ea802de17def8869c12e8885752f6c1fc530f6371e6e3c3cb784ef7ab2821cfac05fd72a2a9c87cffbde668691cd145ed1db0d633377b307702bc53b7e1c', 'ACTIVE'),
  ('33333333-3333-4333-8333-333333333304', 'souvenir@hosifest.test', 'Dev Souvenir',
   'scrypt$fa4bfdc897ce5ab9e710ffa6f47a2814$fa31d31771613884a11ac87c9c9404fb7aaf207b959f0af29d3f976e3a2762a10cd533b8ac737101eb72c2cdf0f5b349d6b1ebb1285ad86121b40e359efce25d', 'ACTIVE')
ON CONFLICT (lower(email)) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
  FROM users u
  JOIN roles r ON r.code = 'ADMIN'
 WHERE u.email = 'admin@hosifest.test'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
  FROM users u
  JOIN roles r ON r.code = 'FINANCE'
 WHERE u.email = 'finance@hosifest.test'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
  FROM users u
  JOIN roles r ON r.code = 'ATTENDANCE'
 WHERE u.email = 'checkin@hosifest.test'
ON CONFLICT DO NOTHING;

-- No SOUVENIR role exists in rbac.ts. Souvenir catalog admin requires
-- config:write, which only ADMIN has, so this operator gets ADMIN rather than
-- a role that cannot perform its own job.
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
  FROM users u
  JOIN roles r ON r.code = 'ADMIN'
 WHERE u.email = 'souvenir@hosifest.test'
ON CONFLICT DO NOTHING;

